# Generated by Django 4.1.7 on 2023-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_rename_user_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.AddField(
            model_name='freightcompany',
            name='associate_companies',
            field=models.ManyToManyField(to='freight.factory'),
        ),
    ]
